# Generated by Django 2.1.7 on 2020-06-10 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('clipURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clip',
            name='fav_clips',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='shortyclipsAPI.ClipUser'),
        ),
        migrations.AddField(
            model_name='clip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortyclipsAPI.ClipUser'),
        ),
    ]
