# Generated by Django 2.1.7 on 2020-06-13 17:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clipuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, max_length=10, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='clip',
            name='fav_clips',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clipuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
