# Generated by Django 2.1.7 on 2020-06-14 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0005_auto_20200614_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 16, 31, 48, 419967, tzinfo=utc)),
        ),
    ]
