# Generated by Django 2.1.7 on 2020-06-14 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0007_auto_20200614_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortyclipsAPI.Clip'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 16, 39, 22, 112659, tzinfo=utc)),
        ),
    ]
