# Generated by Django 2.1.7 on 2020-06-18 02:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0008_auto_20200614_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 2, 1, 39, 717807, tzinfo=utc)),
        ),
    ]
