# Generated by Django 3.0.7 on 2020-06-18 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0009_auto_20200618_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
