# Generated by Django 3.0.7 on 2020-07-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortyclipsAPI', '0012_auto_20200705_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchItem', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
